-- AlterEnum
ALTER TYPE "Target" ADD VALUE 'LEGS';
ALTER TYPE "Target" ADD VALUE 'BACK';
ALTER TYPE "Target" ADD VALUE 'CHEST';
ALTER TYPE "Target" ADD VALUE 'SHOULDERS';
ALTER TYPE "Target" ADD VALUE 'BICEPS';
ALTER TYPE "Target" ADD VALUE 'TRICEPS';
ALTER TYPE "Target" ADD VALUE 'ABS';
